[package]
name = "pocketvec_sqlite"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "pocketvec0"

[dependencies]
sqlite-loadable = { version = "0.0.6-alpha.6" }
byteorder = "1"
thiserror = "1"
log = "0.4"
env_logger = "0.11"
